language: node_js
node_js:
- 4
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: gZuLDK8yr5USxSSZMp6qOGNqRpdiFEuf/Fc0fOtIyAgST2/PORHMIY+tKLfSDyq5UPy7jmJPEg+QB7dqcFOWFBDP4zbksmtUb8foL6f6Lt/9mDGbEMeuOag9d5MN/PS0/9dH7n+onfsXnsVsk15D2+rLaL6hf1ulcmUONtUwOr3v9LWgvBNO0mAmMxyb5Uviy5OBnCIG2mj3kHY1PqmGwrRDRDYXJlrRrebJIs+hMxfHqc+hyQ+SwLVH0BpmYBrWXR75G7+SzfS6g2SXLUIzNvUpjycAsTOOwr3esx+bGodZt+TdqjmpZPBJPbMq2rjJ3KpiZSdY53rZ8fvmNxE91mdLObmD0VX6sQ5Aiaty8wuFJvfBuRwFasEqtzIBYp8PWBZOsYy7y+Qh0+aXPyJIwunW1BhrVN+V3FJOPJdAOgCyNJC5+w++ktyclQQwpHtB+iW8Wz3oF12M0ier4PeKDX8UwZTUmqZQUrVy45THgSBEr0Nvtw52Rocpkurf/vCBYPZaqpTxldsMBGMkn9LgH8HbZLSlqdT6C8QqiuXZFRo1ieWnrRPEaCTAlrzOZykRzbpDyaw0CeNraxRmgyakiG0JsRhu405unztMLSFEgcyKeb8iey4ZD5dlJxyZg4vvCLOot21j77TJEXjTKY2MsLcaBTXsOpPWLAsEjCjTufg=
  on:
    tags: true
    repo: Brightspace/frau-sass-importer
