language: node_js
node_js:
- 4
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: hyhSo1jEzrCp9qZKLt2i47vdn5ga++eNiIdx7FX/XYk82xNxPR/4e8lKqBwDGLVJsA8fDX9QnvWzLipv3bnudvIvGDy8NIJy8YOswn466H1dbOLcFxbqRT+C7SS7S0R2aAmkI7bUhClE4HQT0gfYcjtg0rOGdbMpAha96dG/8KGJYFvsnC9nh1Q2MflLmhMT/1l8qvtt+GDvHaEF6YJYd9ryrwZP2aNuwHrmlA32Cor5TdoQ+uuZe7rk2oE/X2F73Sgp1viC8GcbiFEZPMsGWGCEPWHArrVQ4iNNdskTtq5BhNTfouteTScBzKROJ5TsNWy5J2T5jAxESjmvYXQYoZqE1XpzaqKt7l93c7ueAFKaOJ+AvGzGfovCMIPoHC9BxeZrmxo6LMlqOryHFLjvfGKgGeOY71EdevOrXP+p065fdfWuZagWLVILSvE23Ko/9MTslV6f5zZryPlKLFLgL01PQFttKE8YIBOqkrmb0mmEtLO60XDBPBnrrvWMVGHfgH1gH4i6X+8I6P6Ykmb30ExPGVVyb0I+KvQh4C+uutKRLGDlKtJXM6JJUXfo4Qt6pHohusaF9SldnQPt5RS/88keWikM3HYAQnPqntGyhusHJKhjlH6VexhuptKpm7YfA8BA8TgIwCcPWCfyduzrUWjoJmR0b7ceNwyRtv88XGI=
  on:
    tags: true
    repo: Brightspace/frau-sass-importer
