language: node_js
node_js:
  - 4
  - 6
  - 8
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: dc76......9627
    secure: lcy3GJuYXECvZw1GZ2FDwP/V20XBzvYFivkVlZjBagu3jOdDb/zbTQBuQn6bWbemU+lRpqdbNijd+gjFagNP3tFR9nka+maZcXIxMf6eb49WD9T1SsPFNnqATGhCApYTWcK/YYehsyrDKRqb3JuCXA/OuKJj5laMggz916g5xD7kUg7gxuEDngAPzrEbftoKE2QYftI849abh40hAsAcVxsnYb6oUfvGhvk9z6xhhtYEhnId3+AMoeE8M8CFOrd1f/1P4zKSfWVsecM2pswSaj++hVwgUYnqQe4G1uLd+EmEiIOuOdmqk3ftr22UL4Ez8sW0hbS1KP/J7WUs8wS2frfSill5HAGhSVeTs+SWOM6/o/sfPSTaxn31aVsBBn0+oESYsPNAS+2MzbjoMJWTm0Y/2JhyOdl9Mn4NX6cgtYDyGAt0bWndsau1un1TxT6WD17qH9IinyD6chONtAPM+MRIiYa6dShCydj+tufcM7OEPK4/ySqjSbO5KziLhDvotXyP6EFrOZKFXXoB8i44JqiqviVN8Z2ioXwLNHNuwzUc+iIFvdoJV5Qv7MyZ3nW17r5ZHaXNwcGQSBGvj7g3ZV7UxdUt3tkeH9hcRtplyeOJGV3iZl0h4HC3+AqvGmWqJdCRKCvIF78ZFnjgKnlveHwbvbOPfiSUVss5/pExRnM=
  on:
    tags: true
    repo: Brightspace/frau-sass-importer
    node: 8
