name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: [self-hosted, Linux, AWS]
    steps:
      - name: Checkout Code
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
            node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Lint and Test
        run: npm run test
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
